ALTER TABLE "public"."User"
  ALTER COLUMN "email" DROP NOT NULL,
  ALTER COLUMN "passwordHash" DROP NOT NULL;

ALTER TABLE "public"."User"
  ADD COLUMN IF NOT EXISTS "guest" BOOLEAN NOT NULL DEFAULT false;