-- AlterTable
ALTER TABLE "public"."Bot" ADD COLUMN     "afternoon" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN     "averageSkill" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "evening" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "morning" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
ADD COLUMN     "night" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ALTER COLUMN "speed" SET DEFAULT 50;
